name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/*-dev.yaml'

env:
  APP_NAME: gpt-web-prompt
  REGISTRY: ${{ secret.DOCKER_REGISTRY}}
  REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  K8S_KUBECTL_VERSION: v1.31.0
  K8S_DEPLOYMENT_NAME: gpt-web-prompt
  K8S_NAMESPACE: gpt
  K8S_CONTAINER_NAME: gpt-web-prompt-app  
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64  
          tags: |
            ${{ env.REGISTRY }}/${{ env.APP_NAME }}:latest