name: Build and Deploy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - ".github/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - ".github/**"

env:
  APP_NAME: gpt-web-prompt
  REGISTRY: ${{ secret.DOCKER_REGISTRY}}
  REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:

  Docker_Build_And_Push:

    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/arm64
        tags: ${{ env.REGISTRY }}/${{ env.APP_NAME }}:latest        